# Settings that are applied to the templates. This file should be copied to
# the base folder of the play and renamed settings.yml, then modified to suit
# your needs.

---
####
# Common
common_upgrade: false
local: 'en_GB.UTF-8'
